# Generated by Django 2.2.3 on 2019-07-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_counties'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counties', models.CharField(max_length=25)),
                ('codes', models.IntegerField()),
            ],
        ),
    ]
