# Generated by Django 2.2.3 on 2019-07-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
