# Generated by Django 2.0.13 on 2019-07-31 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qsessions', '0002_session_created_at'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('social_django', '0008_partial_timestamp'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
