# Generated by Django 2.0.13 on 2019-07-25 19:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableFoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('vitamins', 'Fruits and Vegetables'), ('dairy', 'Milk and Dairy products'), ('cabohydrates', 'Cabohydrates, Starchy foods'), ('proteins', 'Protein'), ('fats and sugars', 'Fats and sugars')], max_length=70)),
                ('price_per_unit', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Available Foods',
            },
        ),
        migrations.CreateModel(
            name='AvailableServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Services Available',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=80)),
                ('mobile_number', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='Foodbusiness',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('manager_name', models.CharField(max_length=80)),
                ('id_number', models.IntegerField()),
                ('residence', models.CharField(max_length=80)),
                ('mobile', models.IntegerField()),
                ('biashara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bizzzzz.Business')),
            ],
            options={
                'verbose_name_plural': 'FoodSupply Business',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Laborbusiness',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('manager_name', models.CharField(max_length=80)),
                ('id_number', models.IntegerField()),
                ('residence', models.CharField(max_length=80)),
                ('mobile', models.IntegerField()),
                ('biashara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bizzzzz.Business')),
            ],
            options={
                'verbose_name_plural': 'Service Business',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='availableservices',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bizzzzz.Laborbusiness'),
        ),
        migrations.AddField(
            model_name='availablefoods',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bizzzzz.Foodbusiness'),
        ),
    ]
