# Generated by Django 2.0.13 on 2019-07-26 19:59

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='biker',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
